language: node_js
node_js:
- 5.3
before_install:
- git config --global user.name "$GIT_USER"
- git config --global user.email $GIT_EMAIL
install: npm install
script: gulp build
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy || false'
env:
  global:
  - secure: jY1WSYXDZWttD8UfNDtLsvGmQECWkKZJLJqCcvLQGHLwgqWr+JyrZkrcm5m7MdAFvdT4iJTirXHX6W3Gqxzv+40GI/GDdQD8+VMTpCxE6lJMehFm1aACUR/VMc8b27eNyyVSUNP+qS1wBk/AJZSNWE1bpqI/84LaRdzjTzT2PlNjtaRZtjXNzsAwnM5vfXKGfY/0d+q6Udb1jmvwTdBOd3PmixhQ2dAZ+uetfl8wi+n3gcZk2wCVGu3hbuJgBqEbmd77WJuzS5YYi47pCX8v9uJBSoowBKrvZY5JHIIYOszxnVR6i9JEUScnKtwritM5fqxu6vSWEdmgdwtW9UWNNBuF0r8ZVm4FSCfoLlvLka+c4ULYXhVqtvROGqeP8xAKk8JE1idzTCRsgjdd16PCAngfY3HypO4MxvuBbkrKxQzQeV64WDJCG3prP3LQleQVy6oegnBRX/hEUtMYaOgFRE5ekhN05r2YRIHYu2FJMqnnMDOuJDLOX4Dnh0rROIMJH3DZN+Ql6+JbIlCvdjJC/Ljclf7CaJLJ+1FVcMjb8y13de7ZCYsfGhtnIDzS+pJxrx2czD0qSMJsHcUL7B7zrj0TzgPEwY0pfaQR3bOuXm54oVK1/m5Fa0+m/216yFlKxX2jzqvu/HgvxUO2bNdXlNen+SlIdD+YWgV99UDdr+Y=
  - GIT_USER='Adrian Haasler García'
  - GIT_EMAIL=dev@adrianhaasler.com
  - GIT_REPO=github.com/ahaasler/mit-license-material-theme.git
